### ISSUE TITLE
App <-> Service Communication failure?

### ISSUE THREAD

**Issue by d3xter** [wuan/bo-android#50]
Minimize the app by pressing the back button and then open the app again:
Result is that the "Lightning-Count" and "time until refresh" is not shown at the top of the screen
and i'm not sure whether the data on the map is still updated or not.

Closing the app completly and reopening fixes the problem

**Comment by wuan** [comment]
Can you specify more details so that i can reproduce the problem.

Just having a look at the log output here
Starting up application
{code}
...
06-16 15:21:56.194  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() entered
06-16 15:21:56.194  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() realtime data
06-16 15:21:56.194  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() set alert event consumer
06-16 15:21:56.195  21078-21078/? V/BO_ANDROID﹕ LocationHandler.enableProvider() NETWORK, minTime: 20000, minDist: 50
06-16 15:21:56.197  21078-21078/? D/BO_ANDROID﹕ LocationHandler enable provider
06-16 15:21:56.197  21078-21078/? V/BO_ANDROID﹕ AlertHandler received location null
06-16 15:21:56.231  21078-21078/? V/BO_ANDROID﹕ AlertHandler.processResult() broadcast result SO 257,4 km
06-16 15:21:56.232  21078-21078/? V/BO_ANDROID﹕ LocationHandler.enableProvider() NETWORK, minTime: 20000, minDist: 50
06-16 15:21:56.234  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() done
06-16 15:21:56.235  21078-21078/? D/BO_ANDROID﹕ Main.onDataUpdate() Result(1084 strikes, Parameter(region 1, duration 60, offset 0), RasterParameters(-15.0000, 0.1378; 69.9591, 0.0928))
06-16 15:21:56.236  21078-21078/? V/BO_ANDROID﹕ StrikesOverlay.addStrikes() #1084
06-16 15:21:56.647  21078-21078/? D/BO_ANDROID﹕ added first alert consumer
06-16 15:21:56.969  21078-21078/? V/BO_ANDROID﹕ AlertHandler received location Location[network 48,137208,11,572785 acc=28 et=+3d6h1m28s864ms {Bundle[mParcelledData.dataSize=644]}]
06-16 15:21:56.997  21078-21078/? V/BO_ANDROID﹕ AlertHandler.processResult() broadcast result SO 257,4 km
{code}
now hitting the back button will leave the app
{code}
06-16 15:22:27.924  21078-21078/? V/BO_ANDROID﹕ Main.onPause()
06-16 15:22:28.355  21078-21078/? V/BO_ANDROID﹕ Main.onStop() remove listeners
06-16 15:22:28.355  21078-21078/? D/BO_ANDROID﹕ removed last data consumer
06-16 15:22:28.355  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() entered
06-16 15:22:28.355  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() done
06-16 15:22:28.369  21078-21078/? D/BO_ANDROID﹕ LocationHandler disable provider
06-16 15:22:28.370  21078-21078/? D/BO_ANDROID﹕ removed last alert consumer
06-16 15:22:28.372  21078-21078/? I/BO_ANDROID﹕ Main: onDestroy() unbind service
{code}

starting the app again

{code}
06-16 15:22:35.217  21078-21078/? V/BO_ANDROID﹕ Main.onCreate()
06-16 15:22:35.222  21078-21078/? D/BO_ANDROID﹕ updateVersionStatus() name=org.blitzortung.android.app, state=NO_UPDATE, configuredVersion=138, currentVersion=138
06-16 15:22:35.273  21078-21078/? D/BO_ANDROID﹕ Main.onStart() service: null
06-16 15:22:35.276  21078-21078/? D/BO_ANDROID﹕ Main.onResume() service: null
06-16 15:22:35.282  21078-21078/? I/BO_ANDROID﹕ AppService.onStartCommand() startId: 3 Intent { cmp=org.blitzortung.android.app/.AppService }
06-16 15:22:35.282  21078-21078/? D/BO_ANDROID﹕ DataServiceBinder.getService() org.blitzortung.android.app.AppService@29dfccac
06-16 15:22:35.282  21078-21078/? I/BO_ANDROID﹕ Main.ServiceConnection.onServiceConnected() org.blitzortung.android.app.AppService@29dfccac
06-16 15:22:35.282  21078-21078/? D/BO_ANDROID﹕ added first data consumer
06-16 15:22:35.282  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() entered
06-16 15:22:35.282  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() realtime data
06-16 15:22:35.282  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() set alert event consumer
06-16 15:22:35.282  21078-21078/? V/BO_ANDROID﹕ LocationHandler.enableProvider() NETWORK, minTime: 20000, minDist: 50
06-16 15:22:35.290  21078-21078/? D/BO_ANDROID﹕ LocationHandler enable provider
06-16 15:22:35.290  21078-21078/? V/BO_ANDROID﹕ AlertHandler received location null
06-16 15:22:35.332  21078-21078/? V/BO_ANDROID﹕ AlertHandler.processResult() broadcast result SO 257,4 km
06-16 15:22:35.334  21078-21078/? V/BO_ANDROID﹕ LocationHandler.enableProvider() NETWORK, minTime: 20000, minDist: 50
06-16 15:22:35.341  21078-21078/? V/BO_ANDROID﹕ AppService.configureServiceMode() done
06-16 15:22:35.342  21078-21078/? D/BO_ANDROID﹕ Main.onDataUpdate() Result(1084 strikes, Parameter(region 1, duration 60, offset 0), RasterParameters(-15.0000, 0.1378; 69.9591, 0.0928))
06-16 15:22:35.345  21078-21078/? V/BO_ANDROID﹕ StrikesOverlay.addStrikes() #1084
06-16 15:22:35.781  21078-21078/? D/BO_ANDROID﹕ added first alert consumer
06-16 15:22:36.178  21078-21078/? V/BO_ANDROID﹕ AlertHandler received location Location[network 48,137202,11,572789 acc=28 et=+3d6h2m8s32ms {Bundle[mParcelledData.dataSize=652]}]
06-16 15:22:36.206  21078-21078/? V/BO_ANDROID﹕ AlertHandler.processResult() broadcast result SO 257,4 km
{code}

Here everything works as expected. The service is disconnected/connected correctly.

**Comment by d3xter** [comment]
Ok, will try it at home again and post the logs if it happens again

**Comment by d3xter** [comment]
Running the current master i get:

```
06-16 21:22:34.253    5997-5997/org.blitzortung.android.app V/MapActivity﹕ Recycling map object.
06-16 21:22:34.253    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ Main.onCreate()
06-16 21:22:34.254    5997-5997/org.blitzortung.android.app D/BO_ANDROID﹕ updateVersionStatus() name=org.blitzortung.android.app, state=NO_UPDATE, configuredVersion=137, currentVersion=137
06-16 21:22:34.301    5997-5997/org.blitzortung.android.app D/BO_ANDROID﹕ Main.onStart() service: null
06-16 21:22:34.303    5997-5997/org.blitzortung.android.app D/BO_ANDROID﹕ Main.onResume() service: null
06-16 21:22:34.306    5997-5997/org.blitzortung.android.app I/BO_ANDROID﹕ AppService.onStartCommand() startId: 3 Intent { cmp=org.blitzortung.android.app/.AppService }
06-16 21:22:34.306    5997-5997/org.blitzortung.android.app D/BO_ANDROID﹕ DataServiceBinder.getService() org.blitzortung.android.app.AppService@b8a2dff
06-16 21:22:34.307    5997-5997/org.blitzortung.android.app I/BO_ANDROID﹕ Main.ServiceConnection.onServiceConnected() org.blitzortung.android.app.AppService@b8a2dff
06-16 21:22:34.307    5997-5997/org.blitzortung.android.app D/BO_ANDROID﹕ added first data consumer
06-16 21:22:34.307    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ AppService.configureServiceMode() entered
06-16 21:22:34.307    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ AppService.configureServiceMode() realtime data
06-16 21:22:34.307    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ AppService.configureServiceMode() set alert event consumer
06-16 21:22:34.307    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ LocationHandler.enableProvider() NETWORK, minTime: 20000, minDist: 50
06-16 21:22:34.309    5997-5997/org.blitzortung.android.app D/BO_ANDROID﹕ LocationHandler enable provider
06-16 21:22:34.309    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ AlertHandler received location null
06-16 21:22:34.314    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ LocationHandler.enableProvider() NETWORK, minTime: 20000, minDist: 50
06-16 21:22:34.315    5997-5997/org.blitzortung.android.app V/BO_ANDROID﹕ AppService.configureServiceMode() done
06-16 21:22:34.315    5997-5997/org.blitzortung.android.app D/BO_ANDROID﹕ added first alert consumer
06-16 21:22:34.339    5997-5997/org.blitzortung.android.app I/MapActivity﹕ Handling network change notification:CONNECTED
06-16 21:22:34.339    5997-5997/org.blitzortung.android.app E/MapActivity﹕ Couldn't get connection factory client
```

**Comment by d3xter** [comment]
Not sure whether it is related to the fact that i dont have the google api key to display the map

**Comment by wuan** [comment]
The service is not used for online operation any more. Closing for now.
